### ISSUE TITLE
Could not find "custom/waybar-scrolling-mpris" module definition in config file

### ISSUE THREAD

**Issue by bluebyt** [sicista33/waybar-scrolling-mpris#4]
I get this error:
Could not find "custom/waybar-scrolling-mpris" module definition in config file: /etc/xdg/waybar/config.jsonc
Why it doesn't look here: 
~/.config/waybar/?  

Location of the module:  
/.config/waybar/modules/waybar-scrolling-mpris

Waybar config:
```
    "custom/waybar-scrolling-mpris": {
    "format": "{}",
    "display-format": "{icon}  {artist} - {title}",
    "exec": "~/.config/waybar/modules/waybar-scrolling-mpris",
    "icons": {
        "Paused": "",
        "Playing": "▶",
        "Stopped": "■",
    },
    "length": 40,
```

**Comment by sicista33** [comment]
When looking for a default config file, it searches through the [list](https://github.com/Alexays/Waybar/wiki/Configuration) in order. 
In your case, the issue occurred because it found the '/etc/xdg/waybar/config.jsonc', and therefore did not search other paths.

Remove all custom module config files except for the one you want, or modify the Waybar config to pass the config file path as a command line argument.

**Comment by bluebyt** [comment]
For a workaround I copy my config here and it works:
/etc/xdg/waybar/config.jsonc

I saw this, but I don't understand, where I need to put this line? 
You can pass the path to the module config file as a command-line argument. e.g)
```
"exec": "~/.config/hypr/UserScripts/waybar-scrolling-mpris ~/.config/waybar/modules"
```

**Comment by sicista33** [comment]
When this module is executed, it tries to parse the config file that contains the definition of this module.

If you defined the "custom/waybar-scrolling-mpris" module in `/etc/xdg/waybar/config.jsonc`, you can write "exec" field of module's definition in `/etc/xdg/waybar/config.jsonc` like this:
```
"exec": "~/.config/hypr/UserScripts/waybar-scrolling-mpris /etc/xdg/waybar/config.jsonc"
```

However, since `/etc/xdg/waybar/config.jsonc` is the default config file, you can write just 
```
"exec": "~/.config/hypr/UserScripts/waybar-scrolling-mpris"
```

**Comment by bluebyt** [comment]
Ok I understand I need to put the path in the config file like this:

```
    "custom/waybar-scrolling-mpris": {
    "format": "{}",
    "display-format": "{icon}  {artist} - {title}",
    "exec": "~/.config/hypr/UserScripts/waybar-scrolling-mpris ~/.config/waybar/config.ini",
    "icons": {
        "Paused": "",
        "Playing": "▶",
        "Stopped": "■",
    },
    "length": 15
},
```
Thanks for your help!
